added small test for cloverleaf in CI
OP-DSL/OPS pull request #232
Opened 2024-05-23 22:55 UTC by Ashutosh-Londhe

2024-05-24 08:16 UTC, reguly requested changes
This should be applicable to cloverleaf 2D as well. Why did you comment out the dev_seq and dev_mpi versions?

2024-05-24 10:04 UTC, Ashutosh-Londhe commented
> This should be applicable to cloverleaf 2D as well. Why did you comment out the dev_seq and dev_mpi versions?

The changes are done for Cloverleaf 2D only. Cloverleaf 3D already runs smaller problem by defualt.
Stefano suggested to comment dev version from CI. Should i enable them again?

2024-05-24 10:24 UTC, Ashutosh-Londhe commented
enabled dev version for testing

2024-05-25 23:03 UTC, gihanmudalige approved these changes

2024-05-26 10:07 UTC, merged